apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-helm-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-helm-cicd-demo
  template:
    metadata:
      labels:
        app: sample-helm-cicd-demo
    spec:
      containers:
        - image: mydevopstechlabs.jfrog.io/mydevopstechlabs-backend-release-local/com.mydevopstechlabs.hms/demo:35
          name: sample-helm-cicd-demo
          resources:
            limits:
              cpu: 500m
              memory: 1Gi 
            requests:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sample-helm-cicd-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sample-helm-cicd-demo
