apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-helm-cicd-demo:31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-helm-cicd-demo:31
  template:
    metadata:
      labels:
        app: sample-helm-cicd-demo:31
    spec:
      containers:
        - image: mydevopstechlabs.jfrog.io/mydevopstechlabs-backend-release-local/com.mydevopstechlabs.hms/demo:32
        name: sample-helm-cicd-demo:31
        resources:
            limits:
              cpu: 500m
              memory: 1Gi 
            requests:
              cpu: 500m
              memory: 1Gi
        ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-helm-cicd-demo:31
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sample-helm-cicd-demo:31
